In [1]:
! print('Hello World')

/bin/bash: -c: line 1: syntax error near unexpected token `'Hello World''
/bin/bash: -c: line 1: ` print('Hello World')'


In [2]:
! nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


## 00. PyTorch Fundamentals:

Resource notebook: notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

In [3]:
import torch
print(torch.__version__)

2.1.0+cu118


In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## Introduction to Tensors

### Creating Tensors

PyTorch tensors are created using torch.tensor: https://pytorch.org/docs/stable/tensors.html

In [5]:
# scalar
# Different kinds of tensors, this block is for scalar tensors

scalar = torch.tensor(7)
scalar

tensor(7)

In [6]:
scalar.ndim

0

In [8]:
# Get tensor back as Python int
scalar.item()

7

In [9]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [10]:
# scalar vs. vector vs. matrix vs. tensor

In [11]:
vector.ndim

1

In [12]:
vector.shape

torch.Size([2])

In [13]:
# MATRIX:
MATRIX = torch.tensor([[7,8],
                      [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [14]:
MATRIX.ndim

2

In [15]:
MATRIX.shape

torch.Size([2, 2])

In [16]:
MATRIX[0]

tensor([7, 8])

In [17]:
MATRIX[1]

tensor([ 9, 10])

In [18]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 5, 7],
                        [1, 2, 4]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 5, 7],
         [1, 2, 4]]])

In [19]:
TENSOR.ndim

3

In [20]:
TENSOR.shape

torch.Size([1, 3, 3])

In [21]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 5, 7],
        [1, 2, 4]])

In [22]:
# it means a 1 3x3 tensor

### Random Tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

Torch random tensors - https://pytorch.org/docs/stable/generate/torch.rand.html

In [25]:
# Create a random tensor with pytorch of size/shape (3,4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.6267, 0.7311, 0.9853, 0.6138],
        [0.6424, 0.2056, 0.3747, 0.0427],
        [0.8297, 0.6133, 0.7820, 0.6925]])

In [26]:
random_tensor.ndim

2

In [28]:
random_tensor = torch.rand(1, 10, 10)
random_tensor

tensor([[[0.7362, 0.2688, 0.7484, 0.6790, 0.7604, 0.4195, 0.6988, 0.2733,
          0.2209, 0.3943],
         [0.8109, 0.2106, 0.2013, 0.1648, 0.8531, 0.4919, 0.5686, 0.9730,
          0.2761, 0.3545],
         [0.3060, 0.2407, 0.0552, 0.2699, 0.3406, 0.5251, 0.2026, 0.4810,
          0.7957, 0.0070],
         [0.4426, 0.6533, 0.8882, 0.3103, 0.1705, 0.3276, 0.3350, 0.3256,
          0.2503, 0.2187],
         [0.3031, 0.4332, 0.2618, 0.1295, 0.9478, 0.1529, 0.0982, 0.8199,
          0.2865, 0.9268],
         [0.7869, 0.9153, 0.1118, 0.6998, 0.6312, 0.2670, 0.9998, 0.5567,
          0.4602, 0.5263],
         [0.9058, 0.1272, 0.1749, 0.0535, 0.4403, 0.0077, 0.1128, 0.5998,
          0.3985, 0.0710],
         [0.6270, 0.5145, 0.5791, 0.1377, 0.4147, 0.9587, 0.1294, 0.3060,
          0.9178, 0.1348],
         [0.3493, 0.9888, 0.7522, 0.4302, 0.3416, 0.5675, 0.8619, 0.9060,
          0.3048, 0.8963],
         [0.4231, 0.5617, 0.7374, 0.8552, 0.6077, 0.5681, 0.8381, 0.8095,
          0.0490,

In [29]:
random_tensor.ndim

3

In [30]:
random_tensor = torch.rand(3,3,3)

In [31]:
random_tensor.ndim

3

In [32]:
random_tensor

tensor([[[0.2878, 0.7918, 0.8073],
         [0.5083, 0.5862, 0.4983],
         [0.7350, 0.0770, 0.4809]],

        [[0.1428, 0.8252, 0.5381],
         [0.8900, 0.6806, 0.7586],
         [0.4242, 0.6000, 0.3969]],

        [[0.2718, 0.2592, 0.5087],
         [0.4003, 0.0395, 0.3156],
         [0.8039, 0.5665, 0.9678]]])

In [33]:
# Create random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=[224, 224, 3]) # height, width, color channels
random_image_size_tensor

tensor([[[0.0917, 0.3310, 0.9589],
         [0.0456, 0.1578, 0.2382],
         [0.7578, 0.0199, 0.8462],
         ...,
         [0.4705, 0.5437, 0.7697],
         [0.0531, 0.1822, 0.4015],
         [0.4390, 0.7820, 0.5891]],

        [[0.1661, 0.1998, 0.8496],
         [0.2667, 0.5474, 0.3130],
         [0.1595, 0.4072, 0.5206],
         ...,
         [0.8617, 0.1922, 0.4195],
         [0.1632, 0.9708, 0.1098],
         [0.4308, 0.2788, 0.2860]],

        [[0.5219, 0.6264, 0.4122],
         [0.9285, 0.2192, 0.6139],
         [0.3662, 0.4054, 0.4576],
         ...,
         [0.3683, 0.6947, 0.4644],
         [0.9600, 0.6753, 0.2587],
         [0.6874, 0.0471, 0.4854]],

        ...,

        [[0.1133, 0.1574, 0.3305],
         [0.7405, 0.3860, 0.3471],
         [0.7244, 0.0282, 0.4214],
         ...,
         [0.1553, 0.3667, 0.8731],
         [0.5703, 0.0435, 0.2023],
         [0.3309, 0.9081, 0.0352]],

        [[0.0772, 0.7151, 0.1619],
         [0.2067, 0.5598, 0.8460],
         [0.

In [34]:
random_image_size_tensor.ndim

3

In [35]:
random_image_size_tensor.shape

torch.Size([224, 224, 3])

In [36]:
torch.rand(size=(3,3))

tensor([[0.4420, 0.5464, 0.1319],
        [0.5589, 0.0472, 0.9861],
        [0.5521, 0.4452, 0.9208]])

In [37]:
torch.rand(3,3)

tensor([[0.0288, 0.2718, 0.0318],
        [0.9801, 0.2942, 0.5586],
        [0.1712, 0.4995, 0.6925]])

## Zeros and Ones

In [39]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [41]:
random_tensor = torch.rand(size=(3,4))
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [42]:
# Create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [43]:
ones.dtype

torch.float32

In [45]:
random_tensor.dtype

torch.float32

In [46]:
# Default data type is float 32

### Creating a range of tensors and tensors-like

In [47]:
# Use torch.range() and get deprecated message, use torch.arange() to not get deprecated message
torch.range(0, 10)

<ipython-input-47-74fde6f68c60>:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0, 10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [48]:
torch.__version__

'2.1.0+cu118'

In [49]:
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
torch.arange(1,10)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
one_to_ten = torch.arange(1,11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [52]:
zero_to_thousand_step77 = torch.arange(start=0, end=1000, step=77)
zero_to_thousand_step77

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [55]:
# Creating tensors like
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor Datatypes

**Note:** Tensor datatypes is one of the three big errors you'll run into with PyTorch and deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [56]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None)
float_32_tensor

tensor([3., 6., 9.])

In [57]:
float_32_tensor.dtype

torch.float32

In [58]:
# Float 16 tensor
float_16_tensor = torch.tensor([1,2,3], dtype=torch.float16)
float_16_tensor

tensor([1., 2., 3.], dtype=torch.float16)

In [60]:
# Float 32 tensor
float_32_tensor = torch.tensor([1,2,3],
                               dtype=None,  # what data type is the tensor(e.g. float32 or float16)
                               device=None, # Select device: cpu, cuda, what device is your tensor on
                              requires_grad=False) # whether or not to track gradients with this tensors operations
float_32_tensor

tensor([1, 2, 3])

In [61]:
float_32_tensor.dtype

torch.int64

In [63]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([1., 2., 3.], dtype=torch.float16)

In [65]:
float_16_tensor = float_32_tensor.type(torch.float32)
float_16_tensor, float_16_tensor.dtype

(tensor([1., 2., 3.]), torch.float32)

In [66]:
float_16_tensor = torch.tensor([1,2,3], dtype=torch.float16)
float_16_tensor

tensor([1., 2., 3.], dtype=torch.float16)

In [67]:
float_16_tensor*float_32_tensor

tensor([1., 4., 9.], dtype=torch.float16)

In [68]:
int_32_tensor = torch.tensor([1,2,3], dtype=torch.int32)
int_32_tensor

tensor([1, 2, 3], dtype=torch.int32)

In [69]:
float_32_tensor * int_32_tensor

tensor([1, 4, 9])

In [71]:
int_64_tensor = torch.tensor([1,2,3], dtype=torch.int64)
int_64_tensor, int_64_tensor.dtype

(tensor([1, 2, 3]), torch.int64)

In [73]:
long_int_64_tensor = torch.tensor([1,2,3], dtype=torch.long)
long_int_64_tensor.dtype

torch.int64

In [75]:
dtype_mul=float_32_tensor * long_int_64_tensor

In [76]:
dtype_mul.dtype

torch.int64

### Getting information from tensors:
1. Tensors not right datatype - `tensor.dtype`
2. Tensors not right shape - `tensor.shape`
3. Tensors not on the right device - `tensor.device`

In [77]:
# create a tensor:
some_tensor = torch.rand(3,4)

In [78]:
some_tensor

tensor([[0.3498, 0.5594, 0.4349, 0.5089],
        [0.9912, 0.3067, 0.5202, 0.0731],
        [0.3608, 0.6230, 0.9121, 0.8919]])

In [85]:
# find out details about some tensor:
print(some_tensor)
print(f'data type of tensor: {some_tensor.dtype}')
print(f'shape of tensor: {some_tensor.shape}')
print(some_tensor.size)
print(f'device tensor is on: {some_tensor.device}')


tensor([[0.3498, 0.5594, 0.4349, 0.5089],
        [0.9912, 0.3067, 0.5202, 0.0731],
        [0.3608, 0.6230, 0.9121, 0.8919]])
data type of tensor: torch.float32
shape of tensor: torch.Size([3, 4])
<built-in method size of Tensor object at 0x7a73d9aa1df0>
device tensor is on: cpu


In [84]:
some_tensor.size

<function Tensor.size>

### Manipulating tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix Multiplication

In [106]:
# Create a tensor
tensor = torch.tensor([1,2,3])
# Add 10 to it:
tensor + 10

tensor([11, 12, 13])

In [87]:
# Multiply tensor by 10:
tensor * 10

tensor([10, 20, 30])

In [88]:
# Subtract tensor by 10:
tensor - 10

tensor([-9, -8, -7])

In [89]:
# Try out PyTorch in-built functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [90]:
torch.add(tensor, 10)

tensor([11, 12, 13])

In [91]:
torch.sub(tensor, 10)

tensor([-9, -8, -7])

In [92]:
torch.div(tensor, 10)

tensor([0.1000, 0.2000, 0.3000])

In [93]:
# Divide tensor by 10:

tensor / 10

tensor([0.1000, 0.2000, 0.3000])

### Matrix Multiplication

Two main ways of performing multiplication in neural networks and deep learning:

1. Element-wise multiplication
2. Matrix multiplication (dot product)

Two main rules that performing matrix multiplication needs to satisfy:
1. The **inner dimenstions** must match:
* `(3,2) @ (3,2)` won't work
* `(2,3) @ (2,3)` will work
* `(3,2) @ (2,3)` will work
i.e; number of cols of matrix 1 must match the number of rows of matrix 2

2. The resulting Matrix has the shape of the **outer dimensions**:
* `(2,3) @ (3,2)` -> `(2,2)`
* `(3,2) @ (2,3)` -> `(3,3)`

In [104]:
mat_mul = torch.rand(3,2) @ torch.rand(2,2)
mat_mul, mat_mul.shape

(tensor([[0.2222, 0.4331],
         [0.2469, 1.0054],
         [0.2557, 0.6948]]),
 torch.Size([3, 2]))

In [94]:
# Element wise multiplication:
tensor * tensor

tensor([1, 4, 9])

In [96]:
print(tensor, '*', tensor)
print(f'Equals: {tensor * tensor}')

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [97]:
# Matrix multiplication:
torch.matmul(tensor, tensor)

tensor(14)

In [98]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]


CPU times: user 1.8 ms, sys: 24 µs, total: 1.83 ms
Wall time: 3.84 ms


In [99]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 507 µs, sys: 0 ns, total: 507 µs
Wall time: 385 µs


tensor(14)

In [101]:
%%time
# Also performs matrix multiplication:
tensor @ tensor

CPU times: user 677 µs, sys: 0 ns, total: 677 µs
Wall time: 531 µs


tensor(14)

In [107]:
%%time
# Also performs matrix multiplication but only if the tensor is a matrix~:
torch.mm(tensor, tensor)

RuntimeError: ignored

In [100]:
# in matrix multiplication the number of rows must be equal to the number of columns:


### One of the most common errors in deep learning: shape errors

In [108]:
# Shapes for matrix multiplication:
tensor_A = torch.tensor([[1,2,3],[1,2,3],[1,2,3]])
tensor_B = torch.tensor([[1,2,3],[1,2,3],[1,2,3]])

torch.mm(tensor_A, tensor_B) # Could also use torch.matmul or @

tensor([[ 6, 12, 18],
        [ 6, 12, 18],
        [ 6, 12, 18]])

In [109]:
tensor_A = torch.tensor([[1,2],[3,4],[5,6]])
tensor_B = torch.tensor([[1,2],[3,4],[5,6]])

torch.mm(tensor_A, tensor_B)

RuntimeError: ignored

To fix our tensor shape isses, we can maniupulate the shape of one of our tensors using a transpose.
A transpose switches the axes or dimensions of a given tensor.

In [112]:
tensor_B

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [113]:
tensor_B.T

tensor([[1, 3, 5],
        [2, 4, 6]])

In [114]:
tensor_B.T.shape

torch.Size([2, 3])

In [116]:
print(f'Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}')
print(f'New shapes: tensor_A = {tensor_A.shape}, tensor_B.T = {tensor_B.T.shape}')
print(f'Multiplying: {tensor_A.shape} @ {tensor_B.T.shape}')
print('Output:\n')
output = torch.mm(tensor_A, tensor_B.T)
print(output)
print(f'\nOutput shape: {output.shape}')

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]), tensor_B.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3])
Output:

tensor([[ 5, 11, 17],
        [11, 25, 39],
        [17, 39, 61]])

Output shape: torch.Size([3, 3])
