In [1]:
! print('Hello World')

/bin/bash: -c: line 1: syntax error near unexpected token `'Hello World''
/bin/bash: -c: line 1: ` print('Hello World')'


In [2]:
! nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


## 00. PyTorch Fundamentals:

Resource notebook: notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

In [3]:
import torch
print(torch.__version__)

2.1.0+cu118


In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## Introduction to Tensors

### Creating Tensors

PyTorch tensors are created using torch.tensor: https://pytorch.org/docs/stable/tensors.html

In [5]:
# scalar
# Different kinds of tensors, this block is for scalar tensors

scalar = torch.tensor(7)
scalar

tensor(7)

In [6]:
scalar.ndim

0

In [7]:
# Get tensor back as Python int
scalar.item()

7

In [8]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [9]:
# scalar vs. vector vs. matrix vs. tensor

In [10]:
vector.ndim

1

In [11]:
vector.shape

torch.Size([2])

In [12]:
# MATRIX:
MATRIX = torch.tensor([[7,8],
                      [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [13]:
MATRIX.ndim

2

In [14]:
MATRIX.shape

torch.Size([2, 2])

In [15]:
MATRIX[0]

tensor([7, 8])

In [16]:
MATRIX[1]

tensor([ 9, 10])

In [17]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 5, 7],
                        [1, 2, 4]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 5, 7],
         [1, 2, 4]]])

In [18]:
TENSOR.ndim

3

In [19]:
TENSOR.shape

torch.Size([1, 3, 3])

In [20]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 5, 7],
        [1, 2, 4]])

In [21]:
# it means a 1 3x3 tensor

### Random Tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

Torch random tensors - https://pytorch.org/docs/stable/generate/torch.rand.html

In [22]:
# Create a random tensor with pytorch of size/shape (3,4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.1775, 0.1992, 0.2017, 0.1221],
        [0.1932, 0.4800, 0.8363, 0.8952],
        [0.4475, 0.5210, 0.4061, 0.7075]])

In [23]:
random_tensor.ndim

2

In [24]:
random_tensor = torch.rand(1, 10, 10)
random_tensor

tensor([[[0.4454, 0.9243, 0.9497, 0.1900, 0.8701, 0.6298, 0.3069, 0.8538,
          0.3735, 0.6849],
         [0.5663, 0.4546, 0.9391, 0.8022, 0.5273, 0.3108, 0.2399, 0.8395,
          0.2587, 0.0238],
         [0.9751, 0.0826, 0.0545, 0.1469, 0.7944, 0.7443, 0.4309, 0.9414,
          0.7003, 0.4187],
         [0.6074, 0.0149, 0.7620, 0.1372, 0.4591, 0.7766, 0.0240, 0.0854,
          0.9312, 0.4021],
         [0.1106, 0.5985, 0.3600, 0.8014, 0.8808, 0.9566, 0.8141, 0.9519,
          0.4961, 0.9177],
         [0.2690, 0.8718, 0.4208, 0.4812, 0.9429, 0.5518, 0.9592, 0.3218,
          0.7739, 0.1807],
         [0.1823, 0.2609, 0.4135, 0.8886, 0.4078, 0.4743, 0.5187, 0.2278,
          0.8373, 0.2490],
         [0.6329, 0.2146, 0.4780, 0.4033, 0.5970, 0.4234, 0.9162, 0.0501,
          0.7352, 0.4985],
         [0.3759, 0.7515, 0.9789, 0.7168, 0.6449, 0.6626, 0.0139, 0.1373,
          0.9239, 0.2289],
         [0.2075, 0.6490, 0.1275, 0.2080, 0.9537, 0.7845, 0.1840, 0.3786,
          0.6967,

In [25]:
random_tensor.ndim

3

In [26]:
random_tensor = torch.rand(3,3,3)

In [27]:
random_tensor.ndim

3

In [28]:
random_tensor

tensor([[[0.3752, 0.9046, 0.2956],
         [0.1486, 0.6730, 0.9664],
         [0.8285, 0.0867, 0.9826]],

        [[0.9695, 0.8528, 0.1725],
         [0.6239, 0.7884, 0.8149],
         [0.6306, 0.6029, 0.5891]],

        [[0.9255, 0.6741, 0.7337],
         [0.6460, 0.9315, 0.4507],
         [0.4631, 0.6760, 0.2014]]])

In [29]:
# Create random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=[224, 224, 3]) # height, width, color channels
random_image_size_tensor

tensor([[[0.4525, 0.3520, 0.9405],
         [0.5181, 0.2085, 0.7925],
         [0.6760, 0.6164, 0.2224],
         ...,
         [0.8149, 0.2839, 0.6680],
         [0.1144, 0.2443, 0.3331],
         [0.6485, 0.7889, 0.9493]],

        [[0.2400, 0.9772, 0.9226],
         [0.8512, 0.0729, 0.3372],
         [0.2185, 0.8528, 0.5659],
         ...,
         [0.9213, 0.4787, 0.0940],
         [0.8011, 0.7608, 0.3899],
         [0.6526, 0.1143, 0.3659]],

        [[0.1831, 0.2442, 0.3870],
         [0.1474, 0.0581, 0.6472],
         [0.9281, 0.6258, 0.9758],
         ...,
         [0.6602, 0.2165, 0.8538],
         [0.7613, 0.0303, 0.6355],
         [0.0724, 0.0746, 0.4923]],

        ...,

        [[0.3994, 0.4046, 0.2010],
         [0.2524, 0.2550, 0.4032],
         [0.8962, 0.8607, 0.5280],
         ...,
         [0.4751, 0.1806, 0.0108],
         [0.0054, 0.1812, 0.3913],
         [0.0713, 0.6943, 0.0094]],

        [[0.6321, 0.7390, 0.3954],
         [0.3145, 0.8203, 0.6615],
         [0.

In [30]:
random_image_size_tensor.ndim

3

In [31]:
random_image_size_tensor.shape

torch.Size([224, 224, 3])

In [32]:
torch.rand(size=(3,3))

tensor([[0.2437, 0.4715, 0.0322],
        [0.3013, 0.1164, 0.1424],
        [0.4122, 0.9340, 0.2053]])

In [33]:
torch.rand(3,3)

tensor([[0.3268, 0.1554, 0.6073],
        [0.5490, 0.1144, 0.8441],
        [0.7549, 0.0457, 0.1982]])

## Zeros and Ones

In [34]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [35]:
random_tensor = torch.rand(size=(3,4))
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [36]:
# Create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [37]:
ones.dtype

torch.float32

In [38]:
random_tensor.dtype

torch.float32

In [39]:
# Default data type is float 32

### Creating a range of tensors and tensors-like

In [40]:
# Use torch.range() and get deprecated message, use torch.arange() to not get deprecated message
torch.range(0, 10)

<ipython-input-40-89b10a58f505>:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0, 10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [41]:
torch.__version__

'2.1.0+cu118'

In [42]:
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
torch.arange(1,10)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
one_to_ten = torch.arange(1,11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [45]:
zero_to_thousand_step77 = torch.arange(start=0, end=1000, step=77)
zero_to_thousand_step77

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [46]:
# Creating tensors like
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor Datatypes

**Note:** Tensor datatypes is one of the three big errors you'll run into with PyTorch and deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [47]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None)
float_32_tensor

tensor([3., 6., 9.])

In [48]:
float_32_tensor.dtype

torch.float32

In [49]:
# Float 16 tensor
float_16_tensor = torch.tensor([1,2,3], dtype=torch.float16)
float_16_tensor

tensor([1., 2., 3.], dtype=torch.float16)

In [50]:
# Float 32 tensor
float_32_tensor = torch.tensor([1,2,3],
                               dtype=None,  # what data type is the tensor(e.g. float32 or float16)
                               device=None, # Select device: cpu, cuda, what device is your tensor on
                              requires_grad=False) # whether or not to track gradients with this tensors operations
float_32_tensor

tensor([1, 2, 3])

In [51]:
float_32_tensor.dtype

torch.int64

In [52]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([1., 2., 3.], dtype=torch.float16)

In [53]:
float_16_tensor = float_32_tensor.type(torch.float32)
float_16_tensor, float_16_tensor.dtype

(tensor([1., 2., 3.]), torch.float32)

In [54]:
float_16_tensor = torch.tensor([1,2,3], dtype=torch.float16)
float_16_tensor

tensor([1., 2., 3.], dtype=torch.float16)

In [55]:
float_16_tensor*float_32_tensor

tensor([1., 4., 9.], dtype=torch.float16)

In [56]:
int_32_tensor = torch.tensor([1,2,3], dtype=torch.int32)
int_32_tensor

tensor([1, 2, 3], dtype=torch.int32)

In [57]:
float_32_tensor * int_32_tensor

tensor([1, 4, 9])

In [58]:
int_64_tensor = torch.tensor([1,2,3], dtype=torch.int64)
int_64_tensor, int_64_tensor.dtype

(tensor([1, 2, 3]), torch.int64)

In [59]:
long_int_64_tensor = torch.tensor([1,2,3], dtype=torch.long)
long_int_64_tensor.dtype

torch.int64

In [60]:
dtype_mul=float_32_tensor * long_int_64_tensor

In [61]:
dtype_mul.dtype

torch.int64

### Getting information from tensors:
1. Tensors not right datatype - `tensor.dtype`
2. Tensors not right shape - `tensor.shape`
3. Tensors not on the right device - `tensor.device`

In [62]:
# create a tensor:
some_tensor = torch.rand(3,4)

In [63]:
some_tensor

tensor([[0.0583, 0.0793, 0.7631, 0.2081],
        [0.1280, 0.5701, 0.9780, 0.9711],
        [0.6058, 0.5298, 0.6106, 0.1937]])

In [64]:
# find out details about some tensor:
print(some_tensor)
print(f'data type of tensor: {some_tensor.dtype}')
print(f'shape of tensor: {some_tensor.shape}')
print(some_tensor.size)
print(f'device tensor is on: {some_tensor.device}')


tensor([[0.0583, 0.0793, 0.7631, 0.2081],
        [0.1280, 0.5701, 0.9780, 0.9711],
        [0.6058, 0.5298, 0.6106, 0.1937]])
data type of tensor: torch.float32
shape of tensor: torch.Size([3, 4])
<built-in method size of Tensor object at 0x7c8682a59300>
device tensor is on: cpu


In [65]:
some_tensor.size

<function Tensor.size>

### Manipulating tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix Multiplication

In [66]:
# Create a tensor
tensor = torch.tensor([1,2,3])
# Add 10 to it:
tensor + 10

tensor([11, 12, 13])

In [67]:
# Multiply tensor by 10:
tensor * 10

tensor([10, 20, 30])

In [68]:
# Subtract tensor by 10:
tensor - 10

tensor([-9, -8, -7])

In [69]:
# Try out PyTorch in-built functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [70]:
torch.add(tensor, 10)

tensor([11, 12, 13])

In [71]:
torch.sub(tensor, 10)

tensor([-9, -8, -7])

In [72]:
torch.div(tensor, 10)

tensor([0.1000, 0.2000, 0.3000])

In [73]:
# Divide tensor by 10:

tensor / 10

tensor([0.1000, 0.2000, 0.3000])

### Matrix Multiplication

Two main ways of performing multiplication in neural networks and deep learning:

1. Element-wise multiplication
2. Matrix multiplication (dot product)

Two main rules that performing matrix multiplication needs to satisfy:
1. The **inner dimenstions** must match:
* `(3,2) @ (3,2)` won't work
* `(2,3) @ (2,3)` will work
* `(3,2) @ (2,3)` will work
i.e; number of cols of matrix 1 must match the number of rows of matrix 2

2. The resulting Matrix has the shape of the **outer dimensions**:
* `(2,3) @ (3,2)` -> `(2,2)`
* `(3,2) @ (2,3)` -> `(3,3)`

In [74]:
mat_mul = torch.rand(3,2) @ torch.rand(2,2)
mat_mul, mat_mul.shape

(tensor([[0.2827, 0.1719],
         [0.8805, 0.4402],
         [0.7177, 0.3251]]),
 torch.Size([3, 2]))

In [75]:
# Element wise multiplication:
tensor * tensor

tensor([1, 4, 9])

In [76]:
print(tensor, '*', tensor)
print(f'Equals: {tensor * tensor}')

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [77]:
# Matrix multiplication:
torch.matmul(tensor, tensor)

tensor(14)

In [78]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]


CPU times: user 1.62 ms, sys: 0 ns, total: 1.62 ms
Wall time: 1.54 ms


In [79]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 674 µs, sys: 0 ns, total: 674 µs
Wall time: 563 µs


tensor(14)

In [80]:
%%time
# Also performs matrix multiplication:
tensor @ tensor

CPU times: user 1.7 ms, sys: 11 µs, total: 1.71 ms
Wall time: 1.97 ms


tensor(14)

In [81]:
%%time
# Also performs matrix multiplication but only if the tensor is a matrix~:
torch.mm(tensor, tensor)

RuntimeError: ignored

In [82]:
# in matrix multiplication the number of rows must be equal to the number of columns:


### One of the most common errors in deep learning: shape errors

In [83]:
# Shapes for matrix multiplication:
tensor_A = torch.tensor([[1,2,3],[1,2,3],[1,2,3]])
tensor_B = torch.tensor([[1,2,3],[1,2,3],[1,2,3]])

torch.mm(tensor_A, tensor_B) # Could also use torch.matmul or @

tensor([[ 6, 12, 18],
        [ 6, 12, 18],
        [ 6, 12, 18]])

In [85]:
tensor_A = torch.tensor([[1,2],[3,4],[5,6]])
tensor_B = torch.tensor([[1,2],[3,4],[5,6]])

torch.mm(tensor_A, tensor_B)

RuntimeError: ignored

To fix our tensor shape isses, we can maniupulate the shape of one of our tensors using a transpose.
A transpose switches the axes or dimensions of a given tensor.

In [86]:
tensor_B

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [87]:
tensor_B.T

tensor([[1, 3, 5],
        [2, 4, 6]])

In [88]:
tensor_B.T.shape

torch.Size([2, 3])

In [89]:
print(f'Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}')
print(f'New shapes: tensor_A = {tensor_A.shape}, tensor_B.T = {tensor_B.T.shape}')
print(f'Multiplying: {tensor_A.shape} @ {tensor_B.T.shape}')
print('Output:\n')
output = torch.mm(tensor_A, tensor_B.T)
print(output)
print(f'\nOutput shape: {output.shape}')

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]), tensor_B.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3])
Output:

tensor([[ 5, 11, 17],
        [11, 25, 39],
        [17, 39, 61]])

Output shape: torch.Size([3, 3])


## Finding the min, max, mean, sum, etc (tensor aggregation)

In [90]:
# Create a tensor:
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [91]:
# find the min:
torch.min(x), x.min()

(tensor(0), tensor(0))

In [92]:
# Find the max:
torch.max(x), x.max()

(tensor(90), tensor(90))

In [93]:
# Find the mean:
torch.mean(x.type(torch.float32))

tensor(45.)

In [95]:
x.mean()

RuntimeError: ignored

In [96]:
x.type(torch.float32).mean()

tensor(45.)

In [97]:
# find the sum:
torch.sum(x), x.sum()

(tensor(450), tensor(450))

### Finding the positional min and max

In [98]:
x = torch.arange(0,100,10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [99]:
# Find the position in tensor that has the minimum value with argmin() -> returns index position of target tensor where minimum value occurs
x.argmin()

tensor(0)

In [100]:
x[0]

tensor(0)

In [101]:
# Find the position in tensor that has the maximum value with argmax()
x.argmax()

tensor(9)

In [102]:
x[9]

tensor(90)

In [103]:
# This is helpful when we use the softmax activation function later on

### Reshaping, stacking, squeezing and unsqueezing

* Reshaping - reshpaes an input tensor to a defined shape
* View - return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - remove all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way

In [104]:
# Let's create a tensor
import torch
x = torch.arange(1.,10)
x, x.shape, x.dtype, x.ndim

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]),
 torch.Size([9]),
 torch.float32,
 1)

In [105]:
# Add an extra dimension:
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [106]:
x_reshaped = x.reshape(9,1)
x_reshaped, x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [107]:
x_reshaped = x.reshape(3,3)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

In [108]:
# Change the view:
z = x.view(1,9)
z, z.shape, z.ndim, z.dtype

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 torch.Size([1, 9]),
 2,
 torch.float32)

In [109]:
# changing z changes x, because a view of a tensor shares the same memory as the original input
z = x.view(9,1)
z, x

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [110]:
z[:,0] = 5
z,x

(tensor([[5.],
         [5.],
         [5.],
         [5.],
         [5.],
         [5.],
         [5.],
         [5.],
         [5.]]),
 tensor([5., 5., 5., 5., 5., 5., 5., 5., 5.]))

In [111]:
# Stack tensors on top of each other:
x = torch.arange(0,100,10)
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90],
        [ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90],
        [ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90],
        [ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]])

In [112]:
x_stacked = torch.stack([x,x,x,x], dim=1)
x_stacked

tensor([[ 0,  0,  0,  0],
        [10, 10, 10, 10],
        [20, 20, 20, 20],
        [30, 30, 30, 30],
        [40, 40, 40, 40],
        [50, 50, 50, 50],
        [60, 60, 60, 60],
        [70, 70, 70, 70],
        [80, 80, 80, 80],
        [90, 90, 90, 90]])

In [113]:
x_stacked = torch.stack([x,x,x,x], dim=-1)
x_stacked

tensor([[ 0,  0,  0,  0],
        [10, 10, 10, 10],
        [20, 20, 20, 20],
        [30, 30, 30, 30],
        [40, 40, 40, 40],
        [50, 50, 50, 50],
        [60, 60, 60, 60],
        [70, 70, 70, 70],
        [80, 80, 80, 80],
        [90, 90, 90, 90]])

In [114]:
# torch.squeeze() - removes all single dimensions from a single tensor
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [115]:
x.shape

torch.Size([10])

In [116]:
x.squeeze()

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [117]:
x_reshaped=x.reshape(2,5)
x_reshaped

tensor([[ 0, 10, 20, 30, 40],
        [50, 60, 70, 80, 90]])

In [118]:
x_reshaped_squeezed=x_reshaped.squeeze()
x_reshaped_squeezed

tensor([[ 0, 10, 20, 30, 40],
        [50, 60, 70, 80, 90]])

In [119]:
x_reshaped = x.reshape(1,10)
x_reshaped, x_reshaped.shape

(tensor([[ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]]), torch.Size([1, 10]))

In [120]:
x_reshaped.squeeze(), x_reshaped.squeeze().shape

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.Size([10]))

In [121]:
print(f'previous tensor: {x_reshaped}')
print(f'previous shape: {x_reshaped.shape}')

x_squeezed = x_reshaped.squeeze()
print(f'\nNew tensor: {x_squeezed}')
print(f'New shape: {x_squeezed.shape}')

previous tensor: tensor([[ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]])
previous shape: torch.Size([1, 10])

New tensor: tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])
New shape: torch.Size([10])


In [122]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim(dimension)
print(f'Previous target: {x_squeezed}')
print(f'Previous shape: {x_squeezed.shape}')

# add an extra dimension to the zeroth dimension with unsqueeze:
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f'\nNew Tensor: {x_unsqueezed}')
print(f'New shape: {x_unsqueezed.shape}')

# add an extra dimension to the first dimension with unsqueeze:
x_unsqueezed_1 = x_squeezed.unsqueeze(dim=1)
print(f'\nNew tensor: {x_unsqueezed_1}')
print(f'New shape: {x_unsqueezed_1.shape}')

Previous target: tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])
Previous shape: torch.Size([10])

New Tensor: tensor([[ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]])
New shape: torch.Size([1, 10])

New tensor: tensor([[ 0],
        [10],
        [20],
        [30],
        [40],
        [50],
        [60],
        [70],
        [80],
        [90]])
New shape: torch.Size([10, 1])


In [123]:
# torch.permute() - rearranges the dimesions of a target tensor in a specified order

# torch.permute(input, dims)

x_original = torch.rand(size=(224, 224, 3)) # [height, width, color_channels]

# Permute the original tensor to rearrange the axis (or dim) order

x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f'Previous shape: {x_original.shape}')
print(f'New shape: {x_permuted.shape}')

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [124]:
x_original[0,0,0] = 1
x_permuted[0,0,0]

tensor(1.)

### Indexing (selecting data from tensors)

Indexing with PyTorch is similar to indexing with Numpy

In [125]:
# Create a tensor
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [126]:
# let's index on our new tensor:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [127]:
# index on the middle bracket dim=1
x[0][0]

tensor([1, 2, 3])

In [128]:
x[0, 0]

tensor([1, 2, 3])

In [129]:
# index on the inner bracket:
x[0][0][0]

tensor(1)

In [130]:
x[0,0,0]

tensor(1)

In [131]:
x[0,2,2]

tensor(9)

In [132]:
# You can also use ':' to select all of a target dimension:
x[:,0]

tensor([[1, 2, 3]])

In [133]:
# get all values of 0th and 1st dimensions but only index 1 of the 2nd dimension
x[:,:,1]

tensor([[2, 5, 8]])

In [134]:
# get all values of the 0th dimension but only index 1 of 1st and 2nd dimensions
x[:,1,1]

tensor([5])

In [135]:
# get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0,0,:]

tensor([1, 2, 3])

In [136]:
# index on x to return 9 and 3,6,9
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [137]:
x[0,2,2], x[:,:,2]

(tensor(9), tensor([[3, 6, 9]]))

### PyTorch tensors and NumPy

Numpy is a popular python numerical computing library,
and because of this, PyTorch has functionality to interact with it.

* Data in Numpy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> Numpy -> `torch.tensor.numpy()`

In [138]:
# numpy array to tensor
import numpy as np
import torch

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array) # warning: when converting from numpy -> pytorch, pytorch reflects numpy's default datatype
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [139]:
array.dtype

dtype('float64')

In [140]:
tensor.dtype

torch.float64

In [141]:
torch.arange(1.0, 8.0).dtype

torch.float32

In [142]:
array = np.arange(1.0,10.0)
tensor = torch.from_numpy(array).type(torch.float64)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7., 8., 9.]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float64))

In [143]:
# change the value of array, what will this do to `tensor`?
array = array + 1
array, tensor

(array([ 2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float64))

In [144]:
 # tensor to numpy array:
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [145]:
# change the tensor, what happens to `numpy_tensor`?
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [146]:
# this means they don't share memory~

### Reproducability (trying to take the random out of random)

In short, how a neural network learns is start with random numbers, perform tensor operations, update random numbers to try and make them better representations of the data again and again and again

`start with random numbers -> tensor operations -> update random numbers to try and make better representations of the data -> again -> again -> again...`

To reduce the randomness in neural networks and PyTorch comes the concept of a **random seed**.

Essentially what the random seed does is 'flavor' the randomness

In [147]:
torch.rand(3,3)

tensor([[0.5419, 0.6829, 0.8908],
        [0.9233, 0.8695, 0.4698],
        [0.5853, 0.6161, 0.6077]])

In [148]:
import torch

#Create two random tensors
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.8585, 0.9779, 0.0529, 0.1117],
        [0.1826, 0.9774, 0.7010, 0.9876],
        [0.0722, 0.0960, 0.1137, 0.9421]])
tensor([[0.2495, 0.8053, 0.1305, 0.1788],
        [0.7743, 0.1108, 0.1165, 0.7930],
        [0.5666, 0.9301, 0.6238, 0.0372]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [149]:
# let's make some random but reproducable tensors:
import torch

# set the random seed
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


### Extra Resource for pytorch reproducibility:
* https://pytorch.org/docs/stable/notes/randomness.html

### Running tensors and PyTorch objects on GPUs (and making faster computations)

GPUs = faster computations on numbers, thanks to CUDA + NVIDIA hardware + PyTorch working behind the scenes to make everything hunky dory(good).


### 1. Getting a GPU

1. Easiest - Use Google Colab for a free GPU.
2. Use your own GPU - takes a little bit of setup and requires the investment of purchasing a GPU, there's lots of options
3. Use cloud computing  - GCP, AWS, Azure, these services, allow you to rent computers on the cloud and access them!

For 2,3, PyTorch + GPU drivers (CUDA) takes a little bit of setting up, to do this, refere to PyTorch setup documentation


In [150]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


### Check for GPU access with PyTorch

In [151]:
# check for GPU access with PyTorch
import torch
torch.cuda.is_available()

False

### PyTorch Device Agnostic code:
For PyTorch since it's capable of running on the GPU or CPU, it's best practice to setup device agnostic code
* https://pytorch.org/docs/stable/notes/cuda.html

In [152]:
# Setup device agnostic code
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cpu'

In [153]:
# count number of devices
torch.cuda.device_count()

0

### 3. Putting tensors (and models) on the GPU

The reason we want our tensors/models on the GPU is because GPU results in faster computations.

In [154]:
# Create a tensor (default on the CPU)
tensor = torch.tensor([1,2,3,4])

# Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3, 4]) cpu


In [155]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3, 4])

### 4. Moving tensors back to the CPU

In [156]:
# if tensor is on gpu, can't transform it to numpy
tensor_on_gpu.numpy()

array([1, 2, 3, 4])

In [157]:
# to fix the gpu tensor with NumPy issue, we can first set it to the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3, 4])

## Exercises and Extra-Curriculum
1. Read Documentations on
* `torch.tensor`
* `torch.cuda`
2. Create a random tensor
3. Matrix multiplication
4. random seed
and so on in the link:
https://www.learnpytorch.io/00_pytorch_fundamentals/#exercises