In [1]:
import torch
print(torch.__version__)

2.1.0+cpu


In [2]:
!nvidia-smi

Mon Nov 13 18:13:50 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 529.08       Driver Version: 529.08       CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ... WDDM  | 00000000:01:00.0 Off |                  N/A |
| N/A    0C    P0    N/A /  N/A |      0MiB /  2048MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [3]:
import pandas as pd, numpy as np, matplotlib.pyplot as plt

In [4]:
scalar = torch.tensor(7)
vector = torch.tensor([1,2,3])
scalar.item(), scalar, scalar.ndim, scalar.size, scalar.shape, scalar.dtype

(7, tensor(7), 0, <function Tensor.size>, torch.Size([]), torch.int64)

In [5]:
matrix = torch.tensor([[1,2,3],[4,5,6]])
matrix

tensor([[1, 2, 3],
        [4, 5, 6]])

In [6]:
matrix.ndim, matrix.size, matrix.shape, matrix.dtype

(2, <function Tensor.size>, torch.Size([2, 3]), torch.int64)

In [7]:
tensor = torch.tensor([[[1,2,3], [1,2,3], [1,2,3]]])
tensor

tensor([[[1, 2, 3],
         [1, 2, 3],
         [1, 2, 3]]])

In [8]:
tensor.size

<function Tensor.size>

In [9]:
tensor.shape

torch.Size([1, 3, 3])

In [10]:
tensor.ndim

3

In [11]:
tensor.dtype

torch.int64

In [12]:
matrix.ndim

2

In [13]:
matrix = torch.tensor([[1,2,3],[1,2,3]])

In [14]:
random_tensor = torch.rand(3,5)

In [15]:
random_tensor

tensor([[0.7865, 0.2857, 0.4972, 0.7166, 0.0533],
        [0.5869, 0.1844, 0.5081, 0.9800, 0.2836],
        [0.1813, 0.2471, 0.9928, 0.0316, 0.6587]])

In [16]:
random_tensor = torch.rand(1,10,10)

In [17]:
random_tensor.dtype

torch.float32

In [18]:
random_tensor_image_size = torch.rand(3,244,244)
random_tensor_image_size

tensor([[[0.2892, 0.8225, 0.6972,  ..., 0.3284, 0.0494, 0.0595],
         [0.8986, 0.0941, 0.6642,  ..., 0.0319, 0.4384, 0.0043],
         [0.2547, 0.3014, 0.8604,  ..., 0.5648, 0.3628, 0.6144],
         ...,
         [0.2591, 0.9739, 0.9512,  ..., 0.4191, 0.0480, 0.8647],
         [0.8606, 0.8752, 0.1798,  ..., 0.7131, 0.8636, 0.5851],
         [0.4736, 0.7465, 0.3354,  ..., 0.1107, 0.5550, 0.9829]],

        [[0.0249, 0.7156, 0.1646,  ..., 0.6751, 0.3490, 0.0300],
         [0.9056, 0.4818, 0.9591,  ..., 0.5508, 0.7156, 0.4422],
         [0.5852, 0.9431, 0.1592,  ..., 0.7855, 0.5488, 0.6886],
         ...,
         [0.2925, 0.0571, 0.8346,  ..., 0.1389, 0.6124, 0.1420],
         [0.0370, 0.9396, 0.4303,  ..., 0.8487, 0.4174, 0.3869],
         [0.8059, 0.7293, 0.2667,  ..., 0.2033, 0.8413, 0.4993]],

        [[0.6168, 0.1162, 0.2315,  ..., 0.3623, 0.9699, 0.7363],
         [0.0643, 0.4613, 0.8365,  ..., 0.3394, 0.1894, 0.1491],
         [0.2427, 0.9356, 0.5715,  ..., 0.5406, 0.2638, 0.

In [19]:
random_tensor_image_size.ndim

3

In [20]:
random_tensor_image_size.shape

torch.Size([3, 244, 244])

In [21]:
random_tensor_image_size.dtype

torch.float32

In [22]:
zeros = torch.zeros(2,3)

In [23]:
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [24]:
zeros.dtype

torch.float32

In [25]:
ones = torch.ones(2,3)

In [26]:
ones.dtype

torch.float32

In [27]:
torch.arange(0,10,2)

tensor([0, 2, 4, 6, 8])

In [30]:
ten_zeros = torch.zeros_like(torch.arange(0,10,1))
ten_zeros.shape

torch.Size([10])

In [31]:
fl32 = torch.tensor([1,2,3], dtype = torch.float32)
fl32.dtype

torch.float32

In [33]:
fl32 = torch.tensor([1,2,3],
                    dtype=torch.float32,
                    device='cpu',
                    requires_grad=False)
fl32

tensor([1., 2., 3.])

In [34]:
fl16 = fl32.type(torch.float16)
fl16

tensor([1., 2., 3.], dtype=torch.float16)

In [36]:
mat_mul = torch.rand(3,2) @ torch.rand(2,3)

In [37]:
mat_mul

tensor([[0.3138, 0.8943, 0.8327],
        [0.6707, 0.7398, 0.6324],
        [0.6743, 0.9090, 0.7975]])