In [1]:
import torch

In [2]:
! nvidia-smi

Sun Nov 12 17:25:20 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 529.08       Driver Version: 529.08       CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ... WDDM  | 00000000:01:00.0 Off |                  N/A |
| N/A    0C    P0    N/A /  N/A |      0MiB /  2048MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [3]:
print(torch.__version__)

2.1.0+cpu


In [8]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
! pip install scikit-learn
import sklearn


[notice] A new release of pip is available: 23.2.1 -> 23.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


Defaulting to user installation because normal site-packages is not writeable
  Obtaining dependency information for scikit-learn from https://files.pythonhosted.org/packages/4e/ba/ce9bd1cd4953336a0e213b29cb80bb11816f2a93de8c99f88ef0b446ad0c/scikit_learn-1.3.2-cp311-cp311-win_amd64.whl.metadata
  Obtaining dependency information for scipy>=1.5.0 from https://files.pythonhosted.org/packages/81/d7/d2537d51efb692d0c411e64267ba349e7668d40f5bc73cefe78ccd650dcd/scipy-1.11.3-cp311-cp311-win_amd64.whl.metadata
     ---------------------------------------- 0.0/60.4 kB ? eta -:--:--
     ------ --------------------------------- 10.2/60.4 kB ? eta -:--:--
     ------------------- ------------------ 30.7/60.4 kB 435.7 kB/s eta 0:00:01
     -------------------------------------- 60.4/60.4 kB 643.2 kB/s eta 0:00:00
  Obtaining dependency information for joblib>=1.1.1 from https://files.pythonhosted.org/packages/10/40/d551139c85db202f1f384ba8bcf96aca2f329440a844f924c8a0040b6d02/joblib-1.3.2-py3-none-

In [10]:
scalar = torch.tensor(7)
print(scalar, scalar.dtype, scalar.shape, scalar.ndim)

tensor(7) torch.int64 torch.Size([]) 0


In [11]:
scalar.item()

7

In [12]:
vector = torch.tensor([1,2,3,4])
print(vector, vector.ndim, vector.shape, vector.dtype)

tensor([1, 2, 3, 4]) 1 torch.Size([4]) torch.int64


In [14]:
vector

tensor([1, 2, 3, 4])

In [15]:
matrix = torch.tensor([[1,2,3],[4,5,6]])
print(matrix, matrix.ndim, matrix.shape, matrix.dtype)

tensor([[1, 2, 3],
        [4, 5, 6]]) 2 torch.Size([2, 3]) torch.int64


In [16]:
matrix[0], matrix[1]

(tensor([1, 2, 3]), tensor([4, 5, 6]))

In [17]:
tensor = torch.tensor([[[1,2,3],[3,4,5],[7,8,9]]])
print(tensor)
print(f'the dimensions of tensor: {tensor} is {tensor.ndim}')
print(f'the shape of tensor: {tensor} is {tensor.shape}')
print(f'the data type of tensor: {tensor} is {tensor.dtype}')

tensor([[[1, 2, 3],
         [3, 4, 5],
         [7, 8, 9]]])
the dimensions of tensor: tensor([[[1, 2, 3],
         [3, 4, 5],
         [7, 8, 9]]]) is 3
the shape of tensor: tensor([[[1, 2, 3],
         [3, 4, 5],
         [7, 8, 9]]]) is torch.Size([1, 3, 3])
the data type of tensor: tensor([[[1, 2, 3],
         [3, 4, 5],
         [7, 8, 9]]]) is torch.int64


In [18]:
tensor = torch.tensor([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
tensor.shape

torch.Size([2, 2, 3])

In [19]:
tensor[0], tensor[1]

(tensor([[1, 2, 3],
         [4, 5, 6]]),
 tensor([[ 7,  8,  9],
         [10, 11, 12]]))

In [20]:
tensor[0][0]

tensor([1, 2, 3])

In [21]:
tensor[0][0][0]

tensor(1)

In [22]:
rand_tensor = torch.rand(3,2)
print(rand_tensor, rand_tensor.ndim, rand_tensor.dtype, rand_tensor.shape)


tensor([[0.7311, 0.8435],
        [0.1861, 0.7619],
        [0.7828, 0.9873]]) 2 torch.float32 torch.Size([3, 2])


In [23]:
rand_tensor = torch.rand(1,3,3)
print(rand_tensor, rand_tensor.ndim, rand_tensor.dtype, rand_tensor.shape)

tensor([[[0.2560, 0.7950, 0.5385],
         [0.9957, 0.0984, 0.0449],
         [0.3781, 0.0924, 0.0368]]]) 3 torch.float32 torch.Size([1, 3, 3])


In [24]:
image_size_tensor = torch.rand(3,224,224)
print(image_size_tensor)

tensor([[[6.7646e-01, 6.9911e-01, 3.7898e-01,  ..., 1.4314e-01,
          8.0935e-01, 1.9182e-01],
         [2.1685e-02, 7.4476e-01, 8.1095e-02,  ..., 5.3742e-01,
          2.1810e-01, 4.3979e-01],
         [3.5804e-01, 3.3905e-01, 3.7612e-01,  ..., 6.6153e-01,
          9.5992e-01, 8.7522e-01],
         ...,
         [1.7621e-01, 1.2861e-01, 8.5149e-02,  ..., 4.9602e-01,
          2.7589e-01, 1.8478e-01],
         [6.4506e-01, 8.2559e-01, 2.5945e-02,  ..., 9.0665e-01,
          8.2332e-01, 3.3811e-01],
         [7.1262e-01, 5.4873e-02, 5.3035e-01,  ..., 4.1623e-01,
          6.4749e-02, 8.4032e-01]],

        [[7.5751e-01, 3.7904e-01, 1.3973e-01,  ..., 5.3624e-01,
          8.5775e-01, 6.8330e-01],
         [5.7872e-01, 9.6292e-01, 4.1248e-01,  ..., 2.7610e-01,
          8.2805e-01, 1.7148e-01],
         [7.4421e-01, 1.6800e-01, 2.8269e-01,  ..., 8.6830e-01,
          1.2744e-01, 2.6707e-01],
         ...,
         [4.2072e-01, 3.7099e-01, 8.1464e-01,  ..., 6.7046e-01,
          4.109

In [25]:
image_size_tensor.shape, image_size_tensor.ndim, image_size_tensor.dtype

(torch.Size([3, 224, 224]), 3, torch.float32)

In [26]:
zeros = torch.zeros(3,3)
print(zeros)
print(zeros.ndim, zeros.shape, zeros.dtype)
ones = torch.ones(3,3)
print(ones)
print(ones.ndim, ones.shape, ones.dtype)


tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
2 torch.Size([3, 3]) torch.float32
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
2 torch.Size([3, 3]) torch.float32


In [28]:
print(torch.range(0,10))
print(torch.arange(0,10))

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


C:\Users\HP\AppData\Local\Temp\ipykernel_2156\453247430.py:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  print(torch.range(0,10))


In [29]:
torch.arange(0,10,2)

tensor([0, 2, 4, 6, 8])

In [30]:
torch.arange(start=0, end=10, step=5)

tensor([0, 5])

In [31]:
ten_zeros = torch.zeros_like(torch.arange(0,10))
print(ten_zeros)

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])


In [32]:
five_zeros = torch.zeros_like(torch.arange(0,10,2))
print(five_zeros)

tensor([0, 0, 0, 0, 0])


In [33]:
five_zeros.ndim

1

In [34]:
five_zeros.shape

torch.Size([5])

In [35]:
five_zeros.size

<function Tensor.size>

In [36]:
five_zeros.dtype

torch.int64

In [38]:
tensor_32 = torch.tensor([[1,2,3],[1,2,3]],
                      dtype=None,
                      device=None,
                      requires_grad=False)
tensor_32

tensor([[1, 2, 3],
        [1, 2, 3]])

In [39]:
tensor_16 = torch.tensor([[1,2,3],[1,2,3]],
                      dtype = torch.float16,
                      device = None,
                      requires_grad = False)
tensor_16

tensor([[1., 2., 3.],
        [1., 2., 3.]], dtype=torch.float16)

In [40]:
tensor_32.dtype, tensor_16.dtype

(torch.int64, torch.float16)

In [42]:
tensor_16 = tensor_32.type(torch.float32)
tensor_16.dtype

torch.float32

In [43]:
tensor_32.dtype

torch.int64

In [44]:
tensor_16 = tensor_16.type(torch.float16)

In [45]:
tensor_16

tensor([[1., 2., 3.],
        [1., 2., 3.]], dtype=torch.float16)

In [46]:
tensor_16 = tensor_16.type(torch.float32)
tensor_16.dtype

torch.float32

In [47]:
tensor_16 = tensor_16.type(torch.float64)
tensor_16.dtype

torch.float64

In [48]:
tensor_16 * tensor_32

tensor([[1., 4., 9.],
        [1., 4., 9.]], dtype=torch.float64)

In [49]:
tensor = torch.tensor([1,2,3,4],
                      dtype=None,
                      device=None,
                      requires_grad=False)
tensor

tensor([1, 2, 3, 4])

In [50]:
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.2883, 0.2942, 0.4684, 0.1596],
        [0.6728, 0.6773, 0.4512, 0.4892],
        [0.2885, 0.7776, 0.7176, 0.6012]])

In [51]:
print(some_tensor)
print(f'data type of tensor: {some_tensor.dtype}')
print(f'shape of tensor: {some_tensor.shape}')
print(f'dimensions of tensor: {some_tensor.ndim}')

tensor([[0.2883, 0.2942, 0.4684, 0.1596],
        [0.6728, 0.6773, 0.4512, 0.4892],
        [0.2885, 0.7776, 0.7176, 0.6012]])
data type of tensor: torch.float32
shape of tensor: torch.Size([3, 4])
dimensions of tensor: 2


In [52]:
torch.tensor([[[1,3,4]]]).ndim

3

In [53]:
torch.tensor([[[1,2,3],[1,2,3]]]).ndim

3

In [54]:
torch.tensor([[[[1,2,3]]]]).ndim

4

In [55]:
some_tensor = torch.tensor([1,2,3], dtype=None, device=None, requires_grad=False)
print(some_tensor + 10)
print(some_tensor * 10)
print(some_tensor - 10)
print(some_tensor / 10)
print(some_tensor ** 10)

tensor([11, 12, 13])
tensor([10, 20, 30])
tensor([-9, -8, -7])
tensor([0.1000, 0.2000, 0.3000])
tensor([    1,  1024, 59049])


In [56]:
some_tensor @ some_tensor

tensor(14)

In [59]:
torch.matmul(some_tensor, some_tensor)

tensor(14)

In [60]:
torch.mm(some_tensor, some_tensor)

RuntimeError: self must be a matrix

In [62]:
some_tensor_transpose = some_tensor.T
some_tensor_transpose

tensor([1, 2, 3])